desc "Create a new pull request"
lane :test_create_pull_request do
  response = bitbucket_create_pull_request(
    username: "YOUR_USERNAME_HERE",
    password: "YOUR_PASSWORD_HERE",
    company_host_name: "YOUR_COMPANY_HOST_HERE",
    repository_name: "YOUR_REPOSITORY_NAME_HERE",
    title: "PULL_REQUEST_TITLE_HERE",
    description: "PULL_REQUEST_DESCRIPTION_HERE",
    reviewers: ["FIRST_REVIEWER", "SECOND_REVIEWER"],
    source_branch: "YOUR_SOURCE_BRANCH_HERE",
    destination_branch: "YOUR_DESTINATION_BRANCH_HERE"
  )

  puts response
end

desc "List default reviewers"
lane :test_bitbucket_list_default_reviewers do
  response = bitbucket_list_default_reviewers(
    username: "YOUR_USERNAME_HERE",
    password: "YOUR_PASSWORD_HERE",
    company_host_name: "YOUR_COMPANY_HOST_HERE",
    repository_name: "YOUR_REPOSITORY_NAME_HERE"
  )

  puts response
end
